version: '3.8'

services:
  db:
    image: postgres
    container_name: pg_marcas
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: marcas
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: